### ISSUE TITLE
Passing parameters to threading function in pool

### ISSUE THREAD

**Issue by peddinti** [meh/ruby-thread#19]
I am trying to pass a variable to a function that i am passing through pool.process{function(var)}; however after adding it to pool.process, if the variable changes, the resultant function is getting the changed variable. despite passing var.clone() or making a local copy of var in the function doesn't seem to be working.

Any suggestions on how to solve this problem?

**Comment by contentfree** [comment]
Digging up a grave but where is this capability documented?

**Comment by meh** [comment]
@contentfree https://github.com/meh/ruby-thread/blob/master/lib/thread/pool.rb#L253-L254

Maybe it's a little vague, but it's there 🐼
