### ISSUE TITLE
Thread pooling without queuing?

### ISSUE THREAD

**Issue by waynerobinson** [meh/ruby-thread#28]
I notice that Pool#process seems to queue up each task as its run for execution later. We have a script that has to process around 3 million records which operate at around 100 - 500/s. If we just use pooling it seems like it will create a task object for every one of these jobs that we pass in, a long with a copy of the method attributes.

Is there some way to just block on Pool#process hitting it's pool size limit, rather than queuing them up internally for execution later?

Anyway, just thought I would check if this is already possible with the current library before I go off and implement something (buggy) myself.

Thanks for the great library!

**Comment by waynerobinson** [comment]
I'd just like to mention that I've added a $100 bounty to this project on BountySouce. 
https://www.bountysource.com/issues/5831191-tasks-to-finish-4-2-support

**Comment by kbailey4444** [comment]
Would it be acceptable to add an optional parameter in order to make todo a[SizedQueue](http://ruby-doc.org/stdlib-2.0.0/libdoc/thread/rdoc/SizedQueue.html)? It automatically blocks when it is filled.

**Comment by meh** [comment]
This works now on 0.2.0.

Calling `#wait` on the pool will return `self` when there are idle workers, so you can just `pool.wait.process ...`.

`#wait` can be called with `:idle` or `:done`, `:idle` is the default. `:done` will wait for all the tasks to end.

**Comment by waynerobinson** [comment]
Thanks for this. So just to confirm.

`#wait(:idle)` will wait for any idle worker to become available in the pool?

So basically to prevent queueing up jobs you could just run something like:

```ruby
big_list_of_jobs.each do |job|
  pool.wait.process { job.long_running_method }
end
```

**Comment by waynerobinson** [comment]
Sorry, by the way, I posted the wrong bounty. The actual bounty for this issue is https://www.bountysource.com/issues/5461843-thread-pooling-without-queuing

**Comment by meh** [comment]
@waynerobinson yes, that's exactly how it should work, if it doesn't work do reopen this issue.
