### ISSUE TITLE
rescuing Exception in pool.rb

### ISSUE THREAD

**Issue by kuboj** [meh/ruby-thread#29]
Is rescuing Exception in https://github.com/meh/ruby-thread/blob/master/lib/thread/pool.rb#L57 really necessary? Wouldn't be rescuing StandardError more sufficient? My point is, that  this code
```ruby
Thread.abort_on_exception = true

t = Thread.new do
  sleep 2
  raise "oh noez!"
  sleep 1
end
t.join
```

results in RuntimeError (as expected), but in this case the exception is silently discarded:

```ruby
require 'thread/pool'
Thread.abort_on_exception = true

p = Thread.pool(1)
p.process do
  sleep 2
  raise "oh noez!"
  sleep 1
end
p.shutdown
```

**Comment by meh** [comment]
If the exception isn't rescued the thread in the pool will die, and you don't want that.
