### ISSUE TITLE
memory leak in Thread::Future

### ISSUE THREAD

**Issue by kuboj** [meh/ruby-thread#30]
Line https://github.com/meh/ruby-thread/blob/master/lib/thread/future.rb#L37 causes memory leak, because of passing *self* to ObjectSpace finalizer. Therefore exists reference to this instance of Future which prevents it from being garbage collected. What is the purpose of this finalizer, is it really needed there?

**Comment by meh** [comment]
It's not getting passed `self`, the closure is inside a class method exactly to avoid `self` dangling.
