### ISSUE TITLE
Would tagging releases be possible?

### ISSUE THREAD

**Issue by rud** [meh/ruby-thread#33]
Hi,

If you use the bundler gem skeleton you can do a simple `rake release` to automatically tag git and push the built gem to rubygems. If you want it I'd be happy to provide a PR for this functionality.

**Comment by rud** [comment]
Alternatively, you may just need to run `git push --tags` to get all existing tags from your repository up to github. Currently https://github.com/meh/ruby-thread/releases shows 0 tags, and they're really helpful.

**Comment by meh** [comment]
Yeah, I'll start doing that and backtag things too.

**Comment by rud** [comment]
Awesome, thank you!
