### ISSUE TITLE
A little bit of usage help

### ISSUE THREAD

**Issue by bararchy** [meh/ruby-thread#41]
I got a kind-of-web server application, I do something like this

```ruby
pool = Thread.pool(10) # 10 concurrent users right ?
loop do
  client = server_socket.accept
  pool.process{
    help(client)
  }
end
```

After around 10 connections (even after they are disconnected) the pool will block further connections, do I need to notify the pool somehow that the process is done ? 
like :

```ruby
pool.process{
  help(client)
  poll.im_done!
}
``` 
?

**Comment by bararchy** [comment]
So, it seems The issue was from my side, I used a ```Thread.current.kill``` in my former "Thread Pool" implementation  and this was killing all the Threads in the pool, so after my 10 connections I was out of Threads.

This issue raised another question for me, is there a way to tell the pool to check if it need to repopulate Threads ?

**Comment by meh** [comment]
You should never kill a worker thread yourself, or bad things will happen.

When you trim the pool or you have automatic trimming enabled the unused workers will be killed, and they will be spawned again when needed.

**Comment by meh** [comment]
If you want to clear up the workers, just call `Thread::Pool#trim`, and they will be killed, but never just kill a thread because the pool won't know what happened.

**Comment by bararchy** [comment]
@meh Is there an Overhead to auto_trim ?

**Comment by meh** [comment]
Depends on your workload, trimming happens only if there's nothing queued in the pool, if you get small bursts of processing that happen to be the same size of the pool and the wait time is as long as the time it takes to trim, you'll end up killing all workers to then spawn all the workers back up again.
