### ISSUE TITLE
Thread pool wait 

### ISSUE THREAD

**Issue by balsukrishna** [meh/ruby-thread#43]
Hi,
How to check if all tasks are finished in a pool? I am not explicitly creating tasks  so I don't have variable to use task.finished?
**pool.wait** seem to return after last task consumed, not after it finish.

**Comment by meh** [comment]
If you want to wait for all tasks to finish you have to use `pool.wait(:done)`, if you want to check if the pool is done use `pool.done?`.

**Comment by contentfree** [comment]
If `abort_on_exception` is `true` and I run `pool.wait(:done)` it appears to hang forever if there's an exception. (I don't want open an issue if this is merely a misunderstanding of the interaction between abort_on_exception and pool.wait.)
