### ISSUE TITLE
Should pipe act like an enumerable?

### ISSUE THREAD

**Issue by JelF** [meh/ruby-thread#44]
Currently, pipe supports only data mapping, but i could not find any simple way for rejecting something in the middle of pipe. Parallel reduce implementation would also be nice there imo. And, obliviously, it can support each as an endpoint to

I don't ask to include Enumerable, my questions are
1) Can i alias `|(block)` to `map(&block)` for a kind of consistency
2) Can i implement an `each(&block)`
3) Can i implement `select` and `reject`? Should i alias them (one of them?) for consistency with `|`?
4) What is about `reduce`? Does parallel reduce make any sence in ruby? 
5) Maybe, instead of this, i should write another gem, which would implement parallel features in Enumerable? Or probably make a PR here to somewhere like `thread/core_ext/enumerable`?

**Comment by meh** [comment]
The basic idea of the `Pipe` is to be a set of linked `Queue`s, so yes, it wouldn't be appropriate.

But I like the idea, if you want it to become a `thread/enumera{ble,tor}` I'd be fine with merging it.

**Comment by JelF** [comment]
I will add questions about adding some extensions to thread library here, when i would understand them.
First question is can i add `done!` (or `close_write`) to queues, which would close their write one by one when job is done, so i can understand, that all data was processed and i can release non-enumerables and loops like `each`?

**Comment by meh** [comment]
The `Enumerable` side of things would need to be a new implementation without changing the rest rather than an extension to the already existing `Pipe`.

**Comment by JelF** [comment]
After some analysis, i understood that `ruby-thread` is not a good place for fast collection enumeration for some reasons. Mainly, this should not be solved with ruby threads.
