### ISSUE TITLE
Synchronizing writes across threads

### ISSUE THREAD

**Issue by ravinggenius** [meh/ruby-thread#47]
I'm trying to synchronize writes to a database. It seems as if I can do some in-memory, stateless processing, then call `Thread::Pool#wait` before interacting with the database. Is that how it is meant to be used? If not is there a mechanism to synchronize some action across multiple threads?

**Comment by meh** [comment]
`Thread::Pool#wait` is to wait for the pool to either have an idle worker, or all idle worker.

You'd still need to put the results of those computations somewhere, and you'd still need to use a `Mutex` for that.

Personally I'd just wrap the database connection or whatnot in an object with a `Mutex` and pass that to the workers, so they'll just write to the database when they're done.

Unless you have to do the writes in a specific order, have any more information on what kind of synchronization you need to do?

**Comment by ravinggenius** [comment]
I don't have to do database inserts in any particular order, but some later inserts may contain data which was previously inserted. I played around with `#wait` and figured out it isn't what I wanted. I ended up creating a `Mutex` manually and passing it into the function that wrote to the database.

I was really hoping for an API like below:

``` ruby
pool = Thread.pool(4)
(1..10).each do |n|
  # do something expensive
  pool.synchronize do
    # time to write to the database!
    # everything inside `#synchronize` executes inside a `Mutex`
  end
end
pool.shutdown
```

Would you be interested in that?

**Comment by meh** [comment]
The problem with that is that the `Mutex` would be global for the pool, and the user might want that, or he might need more granularity.

I prefer not to make that kind of decision in the library, but if you don't like passing the `Mutex` to the functions, remember you can inherit from the `Thread::Pool` and add that method yourself :panda_face:

**Comment by ravinggenius** [comment]
No problem. It's not a big deal.
