### ISSUE TITLE
Following example not worked.

### ISSUE THREAD

**Issue by zw963** [meh/ruby-thread#49]
```rb
require 'thread/process'

p = Thread.process {
  loop {
    puts receive.inspect*2
  }
}

p << 42
p << 23
```

When run in ruby 2.3.3 nothing happen, main thread is exit, which cause
Thread.process exit too.  we need append `sleep 1` to end of file, to make 
it worked.

**Comment by meh** [comment]
Live threads don't stop the process from exiting, that's how Ruby works.

**Comment by zw963** [comment]
>> Live threads don't stop the process from exiting, that's how Ruby works.

I know ...., so, need update README to add some sleep ?

**Comment by meh** [comment]
The example is there to show how to use the `Process`, not how to have a script that works, adding a sleep is redundant.

**Comment by zw963** [comment]
@meh , add a runable example in README, maybe better? : )
